momotaro/urls.py
from django.urls import path
from . import views

app_name = 'momotaro'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('user/', views.UserIndexView.as_view(), name='user'),
    path('user/add/', views.UserAddView.as_view(), name='user.add'),
    path('user/update/<int:pk>',views.UserUpdateView.as_view(), name='user.update'),
    path('user/delete/<int:pk>', views.UserDeleteView.as_view(), name='user.delete'),
    path('user/detail/<int:pk>', views.UserDetailView.as_view(), name='user.detail'),
    path('momotaro/', views.momotarocreateform, name='momotaro'),
]

momotaro_study/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('momotaro.urls')),
    path('', include('register.urls')),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('top', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    # User
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<uidb64>/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    # Momotaro
    path('momotaro_create/<int:pk>', views.momotaro_create, name='momotaro_create')
]

momotaro/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class User(models.Model):
    nickname = models.CharField('ニックネーム',max_length=100 ,null=False)
    gender = models.CharField('性別', max_length=10 ,null=True)
    age = models.CharField('年代', max_length=3 ,null=True)
    email = models.EmailField('メールアドレス' ,null=True)
    additional_comments = models.TextField('自由記入欄', max_length=500 ,null=True)
    password = models.CharField('パスワード', max_length=30 ,null=True)
    date = models.DateTimeField('作成日',default=timezone.now)

    def __str__(self):
        return self.nickname

class Momotaro(models.Model):
    goal = models.CharField('目標', max_length=255 ,null=False)
    limit = models.CharField('期限', max_length=20 ,null=False)
    reason = models.CharField('目標を設定した理由', max_length=255 ,null=True)
    additional_comments =  models.TextField('自由記入欄', max_length=500 ,null=True)
    date = models.DateTimeField('作成日', default=timezone.now)
    user = models.OneToOneField(User, on_delete=models.PROTECT)

    def __str__(self):
        return self.goal

register/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager

# Create your models here.
class UserManager(BaseUserManager):
    """ユーザーマネージャー."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """メールアドレスでの登録を必須にする"""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """is_staff(管理サイトにログインできるか)と、is_superuer(全ての権限)をFalseに"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """スーパーユーザーは、is_staffとis_superuserをTrueに"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""
    email = models.EmailField(_('email address'), unique=True)
    nickname = models.CharField(_('ニックネーム'), max_length=50, blank=True)
    age = models.CharField(_('年代'), max_length=5, blank=True)
    gender = models.CharField(_('性別'), max_length=2, blank=True)
    address = models.CharField(_('住所'), max_length=5, blank=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    NICKNAME_FIELD = 'nickname'
    USERAGE_FIELD = 'age'
    USERGENDER_FIELD = 'gender'
    USERADDRESS_FIELD = 'address'

    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')


    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        """username属性のゲッター

        他アプリケーションが、username属性にアクセスした場合に備えて定義
        メールアドレスを返す
        """
        return self.email

class Momotaro(models.Model):
    goal = models.CharField('目標', max_length=255 ,null=False)
    limit = models.CharField('期限', max_length=20 ,null=False)
    reason = models.CharField('目標を達成したい理由', max_length=255 ,null=True)
    additional_comments =  models.TextField('自由記入欄', max_length=500 ,null=True)
    date = models.DateTimeField('作成日', default=timezone.now)
    user = models.OneToOneField(User, on_delete=models.PROTECT)

    def __str__(self):
        return self.goal

momotaro/forms.py
from django import forms
from .models import User
from .models import Momotaro

class UserCreateForm(forms.ModelForm):
    accept_check = forms.BooleanField()
    class Meta:
        model = User
        fields = ('nickname', 'gender', 'age','email', 'additional_comments', 'password')

class MomotaroCreateForm(forms.ModelForm):
    class Meta:
        model = Momotaro
        fields = ('goal', 'limit', 'reason', 'additional_comments')

register/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,UserCreationForm
)
from django.contrib.auth import get_user_model
from .models import Momotaro


User = get_user_model()


class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる

class UserCreateForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        fields = ('email', 'nickname')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class UserUpdateForm(forms.ModelForm):
    """ユーザー情報更新フォーム"""

    class Meta:
        model = User
        fields = ('nickname', 'age', 'gender', 'address')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

########## 桃太郎登録 #############
class MomotaroCreateForm(forms.ModelForm):
    """桃太郎登録フォーム"""

    class Meta:
        model = Momotaro
        fields = ('goal', 'limit', 'reason', 'additional_comments')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

momotaro/views.py
from django.shortcuts import render,redirect
from django.views import generic
from django.urls import reverse_lazy
from .forms import UserCreateForm, MomotaroCreateForm
from .forms import MomotaroCreateForm
from .models import User


# Create your views here.
from django.http import HttpResponse

def index(request):
    """TOPページ"""
    return render(request, 'momotaro/index.html')


def about(request):
    """Aboutページ"""
    return render(request, 'momotaro/about.html')


"""ユーザー登録"""
class UserIndexView(generic.ListView):
    model = User
    success_url = reverse_lazy('momotaro:index')

class UserAddView(generic.CreateView):
    model = User
    form_class = UserCreateForm
    success_url = reverse_lazy('momotaro:index')

class UserUpdateView(generic.UpdateView):
    model = User
    form_class = UserCreateForm
    template_name = "momotaro/user_update.html"
    success_url = reverse_lazy('momotaro:index')

class UserDeleteView(generic.DeleteView):
    model = User
    form_class = UserCreateForm
    success_url = reverse_lazy('momotaro:index')

class UserDetailView(generic.DetailView):
    model = User


"""桃太郎登録"""
def momotarocreateform(request):
    """桃太郎登録ページへ"""


    context = {
        "user_form": UserCreateForm,
        "momotaro_form": MomotaroCreateForm,
    }
    return render(request, 'momotaro/momotaro_form.html', context)

register/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.contrib.auth.views import (
    LoginView, LogoutView
)
from django.views import generic
from .forms import (
    LoginForm, UserCreateForm, UserUpdateForm, MomotaroCreateForm
    )
from .models import Momotaro


from django.contrib.auth import get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.http import Http404
from django.shortcuts import redirect, resolve_url
from django.template.loader import get_template
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

# Create your views here.
class Top(generic.TemplateView):
    template_name = 'register/top.html'


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'register/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'register/top.html'

User = get_user_model()

class UserCreate(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'register/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'uidb64': urlsafe_base64_encode(force_bytes(user.pk)).decode('utf-8'),
            'token': urlsafe_base64_encode(force_bytes(user.email)).decode('utf-8'),
            'user': user,
        }

        # テンプレートを使ってメールを組み立てる
        subject_template = get_template('register/mail_template/create/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('register/mail_template/create/message.txt')
        message = message_template.render(context)

        user.email_user(subject, message)  # ユーザーのメール送信メソッド
        return redirect('register:user_create_done')


class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録完了"""
    template_name = 'register/user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'register/user_create_complete.html'

    def get(self, request, **kwargs):
        """uid、tokenが正しければ本登録."""
        token = kwargs.get('token')
        uidb64 = kwargs.get('uidb64')
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            email = force_text(urlsafe_base64_decode(token))
            user = User.objects.get(pk=uid, email=email)
            if user.is_active:    # すでにis_activeがTrueなら、処理は必要ないので404
                raise Http404
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            pass
        else:
            user.is_active = True
            user.save()
            return super().get(request, **kwargs)

        raise Http404

class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class UserDetail(OnlyYouMixin, generic.DetailView):
    model = User
    template_name = 'register/user_detail.html'


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'register/user_form.html'

    def get_success_url(self):
        return resolve_url('register:user_detail', pk=self.kwargs['pk'])

def momotaro_create(request, pk):
    model = Momotaro
    user = User.objects.get(id=pk)

    # 送信内容をもとにフォームを作る。POSTでなければからのフォーム
    form = MomotaroCreateForm(request.POST or None)
    template_name = 'register/momotaro_form.html'
    # method=POST,つまり送信ボタン押下時、入力内容に誤りがなければ
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('register:index')
    # 通常時のページアクセスや、入力内容に誤りがあれば、またページを表示
    context = {
    'form': form
    }
    return render(request, 'register/momotaro_form.html', context)

register/templates/register/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <title>会員登録サンプル</title>
</head>
<body>
    <!-- ナビバー -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'register:top' %}">ホームページ名</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li>
            <a class="nav-item nav-link" href="{% url 'register:user_detail' user.pk %}">ユーザー情報閲覧</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:user_update' user.pk %}">ユーザー情報更新</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:logout' %}">ログアウト</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'register:login' %}">
            ようこそ、ゲスト！ログインはこちら
          </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <!-- メインコンテント -->
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

register/templates/register/login.html
{% extends "register/base.html" %} {% block content %}
<div class="row">
  <!-- 左側、ログインエリア -->
  <div class="card col-md-6">
    <div class="card-body">
      <form action="{% url 'register:login' %}" method="POST">
        {{ form.non_field_errors }} {% for field in form %} {{ field }} {{ field.errors }}
        <hr> {% endfor %}
        <button type="submit" class="btn btn-success btn-lg btn-block">ログイン</button>
        <input type="hidden" name="next" value="{{ next }}" /> {% csrf_token %}
      </form>
    </div>
  </div>
  <!-- 左側、ログインエリアおわり -->

  <!-- 右側、会員登録エリア -->
  <div class="card col-md-6">
    <div class="card-body">
      <a href="{% url 'register:user_create' %}" class="btn btn-success btn-lg btn-block">会員登録</a>
    </div>
  </div>
  <!-- 右側、会員登録エリアおわり -->
</div>
{% endblock %}

register/templates/register/momotaro_form.html
{% extends "register/base.html" %}
{% block content %}
<form class="" action="" method="POST">
  <table class="table">
    <tbody>
      <tr>
        <th>ニックネーム</th>
        <td>{{ user.nickname }}</td>
      </tr>
      <tr>
        <th>年齢</th>
        <td>{{ user.age }}</td>
      </tr>
      <tr>
        <th>性別</th>
        <td>{{ user.gender }}</td>
      </tr>
      <tr>
        <th>住所</th>
        <td>{{ user.address }}</td>
      </tr>
      <!-- これより上がユーザー情報で登録されていた項目で、下がここで登録してもらいたい項目 -->
      {% for field in form %}
        <tr>
          <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
          <td>{{ field }} {{ field.errors }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <button type="submit" name="">送信</button>
  {% csrf_token %}
</form>
{% endblock %}

register/templates/register/top.html
{% extends "register/base.html" %}
{% block content %}
<p>ここに、好きな内容を入れる。</p>
{% endblock %}

register/templates/register/user_create.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

register/templates/register/user_create_complete.html
{% extends "register/base.html" %}
{% block content %}
<p>
    本登録が完了しました。<br>
    登録されたメールアドレスとパスワードでログインしてください。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'register:login' %}">ログイン</a>
</p>
{% endblock %}

register/templates/register/user_create_done.html
{% extends "register/base.html" %}
{% block content %}
<p>
    会員登録確認メールを送信しました。まだ、会員登録は完了していません。<br>
    確認メールを送信しましたので、確認メールに記載されているリンクから本登録を行ってください。
</p>
{% endblock %}

register/templates/register/user_detail.html
{% extends "register/base.html" %}
{% block content %}
<table class="table">
  <tbody>
    <tr>
      <th>ニックネーム</th>
      <td>{{ user.nickname }}</td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td>{{ user.email }}</td>
    </tr>
    <tr>
      <th>年齢</th>
      <td>{{ user.age }}</td>
    </tr>
    <tr>
      <th>性別</th>
      <td>{{ user.gender }}</td>
    </tr>
    <tr>
      <th>住所</th>
      <td>{{ user.address }}</td>
    </tr>
  </tbody>
</table>
<a href="{% url 'register:momotaro_create' user.pk %}" class="btn btn-danger">桃太郎として登録する</a>
{% endblock %}

register/templates/register/user_form.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    <table class="table">
        <tbody>
            {% for field in form %}
                <tr>
                    <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
                    <td>{{ field }} {{ field.errors }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-lg" >送信</button>
</form>
{% endblock %}